import CameraIcon from "./CameraIcon";
import ImageIcon from "./ImageIcon";
import ImageGalleryIcon from "./ImageGalleryIcon";
import CaptureIcon from "./CaptureIcon";
import CancelIcon from "./CancelIcon";
import MenuIcon from "./MenuIcon";
import CopyIcon from "./CopyIcon";
import Flip from "./Flip";
import FlashOff from "./Flashoff";
import FlashOn from "./Flashon";
import Edit from './Edit';
import Tick from './Tick';
import Undo from './Undo';
export { CameraIcon,Edit,Tick,Undo,FlashOff,FlashOn, ImageIcon, MenuIcon, CancelIcon, CopyIcon, CaptureIcon, ImageGalleryIcon, Flip };
